<ul>
  <li><a href="https://www.hancockcollege.edu/admissions_records/calendar.php">Academic Calendar</a></li>
  <li><a href="https://www.hancockcollege.edu/academic_departments/index.php">Academic Departments</a></li>
  <li><a href="https://www.hancockcollege.edu/academic_senate/index.php">Academic Senate</a></li>
  <li><a href="https://www.hancockcollege.edu/app/index.php">Academic Policy &amp; Planning (AP&amp;P)</a></li>
  <li><a href="https://www.hancockcollege.edu/accreditation/index.php">Accreditation</a></li>
  <li><a href="https://www.hancockcollege.edu/admissions_records/index.php">Admissions and Records</a></li>
  <li><a href="https://www.hancockcollege.edu/asbg/clubs.php">AHC Clubs</a></li>
  <li><a href="https://www.hancockcollege.edu/veterans/index.php">AHC Veteran Success Center (VSC)</a></li>
  <li><a href="https://www.hancockcollege.edu/aim/index.php">AIM Center</a></li>
  <li><a href="https://www.hancockcollege.edu/gallery/index.php">Art Gallery (Ann Foxworthy Gallery)</a></li>
  <li><a href="https://www.hancockcollege.edu/asbg/index.php">ASBG</a></li>
  <li><a href="https://www.hancockcollege.edu/employees/aux-accounting.php">Auxiliary Accounting Services</a></li>
  <li><a href="https://www.hancockcollege.edu/auxilliarycorp/index.php">Auxiliary Programs Corporation</a></li>
  <li><a href="https://www.hancockcollege.edu/laverne/index.php">Bachelor Programs</a></li>
  <li><a href="https://www.hancockcollege.edu/board/index.php">Board of Trustees</a></li>
  <li><a href="https://www.hancockcollege.edu/board/BoardPolicies.php">Board Policies</a></li>
  <li><a href="http://www.HancockCollegeShop.com">Bookstore</a></li>
  <li><a href="https://www.hancockcollege.edu/bridges/index.php">Bridges to the Baccalaureate&nbsp;</a></li>
  <li><a href="https://www.hancockcollege.edu/public_affairs/public-transportation.php">Bus Service/Transportation</a></li>
  <li><a href="https://www.hancockcollege.edu/minicorps/index.php">California Mini Corps</a></li>
  <li><a href="https://www.hancockcollege.edu/cal-soap/index.php">Cal-SOAP</a></li>
  <li><a href="https://www.hancockcollege.edu/calworks/index.php">CalWORKs</a></li>
  <li><a href="https://www.hancockcollege.edu/campuscruise/index.php">Campus Cruise (Tours)</a></li>
  <li><a href="https://www.hancockcollege.edu/campus_graphics/index.php">Campus Graphics</a></li>
  <li><a href="https://www.hancockcollege.edu/can/index.php">CAN/TRIO</a></li>
  <li><a href="https://hancockcollege.instructure.com/login/saml">Canvas</a></li>
  <li><a href="https://www.hancockcollege.edu/care/index.php">CARE</a></li>
  <li><a href="https://www.hancockcollege.edu/cte/index.php">Career Technical Education (CTE)</a></li>
  <li><a href="https://www.hancockcollege.edu/cjpc/index.php">Career/Job Placement Center (CJPC)</a></li>
  <li><a href="https://www.hancockcollege.edu/public_affairs/Catalog.php">Catalog</a></li>
  <li><a href="https://dfl.hancockcollege.edu/Presidents_Office/docs/CCPD%20Councils%20and%20Committees%20Manual.pdf">CCPD Councils and Committees Manual <span class="far fa-file-pdf"><span class="sr-only">PDF</span></span></a></li>
  <li><a href="https://www.hancockcollege.edu/childrens_center/index.php">Children's Center</a></li>
  <li><a href="http://bannerweb.hancockcollege.edu/prod/pw_sigsched.p_search">Class Search</a></li>
  <li><a href="https://www.hancockcollege.edu/admissions_records/college-now.php">College Now!</a></li>
  <li><a href="https://www.hancockcollege.edu/community_education/index.php">Community Education</a></li>
  <li><a href="https://www.hancockcollege.edu/complaints/index.php">Complaints</a></li>
  <li><a href="https://www.hancockcollege.edu/labs/computer_resources_center/index.php">Computer Resources Center</a></li>
  <li><a href="https://www.hancockcollege.edu/concurrentenrollment/index.php">Concurrent Enrollment</a></li>
  <li><a href="https://www.hancockcollege.edu/contracteducation/index.php">Contract Education</a></li>
  <li><a href="https://www.hancockcollege.edu/cwe/index.php">Cooperative Work Experience (CWE)</a></li>
  <li><a href="https://www.hancockcollege.edu/counseling/index.php">Counseling</a></li>
  <li><a href="https://www.hancockcollege.edu/courserepeatability/index.php">Course Repeatability</a></li>
  <li><a href="https://www.hancockcollege.edu/campus_police/clery.php">Crime Statistics</a></li>
  <li><a href="https://www.hancockcollege.edu/cast/index.php">Crisis Intervention (CAST)</a></li>
  <li><a href="https://www.hancockcollege.edu/degreeworks/index.php">DegreeWorks</a></li>
  <li><a href="https://www.hancockcollege.edu/lap/index.php">Disability Services</a></li>
  <li><a href="https://www.hancockcollege.edu/distance_learning/">Distance Learning</a></li>
  <li><a href="https://www.hancockcollege.edu/dreamact/index.php">Dream Act/AB 540</a></li>
  <li><a href="https://www.hancockcollege.edu/counseling/eap.php">Early Alert</a></li>
  <li><a href="https://www.hancockcollege.edu/ewd/index.php">Economic and Workforce Development</a></li>
  <li><a href="https://www.hancockcollege.edu/campus_police/emergency-prep.php">Emergency Preparedness</a></li>
  <li><a href="https://www.hancockcollege.edu/placement/index.php">English and Math Placement</a></li>
  <li><a href="https://www.hancockcollege.edu/eops/index.php">EOPS</a></li>
  <li><a href="https://www.hancockcollege.edu/academic_departments/languages/esl/index.php">ESL-Credit</a></li>
  <li><a href="https://www.hancockcollege.edu/community_education/noncredit-esl.php">ESL-Noncredit</a></li>
  <li><a href="https://outreach.hancockcollege.edu/Ellucian.ERecruiting.Web.External/Pages/events.aspx">Event Registration</a></li>
  <li><a href="https://www.hancockcollege.edu/facilities/index.php">Facilities</a></li>
  <li><a href="https://www.hancockcollege.edu/cashier_services/index.php">Fees</a></li>
  <li><a href="https://www.hancockcollege.edu/admissions_records/calendar.php">Final Exams</a></li>
  <li><a href="https://www.hancockcollege.edu/financial_aid/index.php">Financial Aid</a></li>
  <li><a href="https://www.hancockcollege.edu/foodshare/index.php">Food Share Because We Care</a></li>
  <li><a href="https://www.hancockcollege.edu/cafyes/index.php">Foster Youth Services</a></li>
  <li><a href="https://www.hancockcollege.edu/testing/ged.php">GED Computer-based Test</a></li>
  <li><a href="https://www.hancockcollege.edu/testing/ged-esp.php">GED: por la computadora</a></li>
  <li><a href="https://www.hancockcollege.edu/testing/gedtranscript.php">GED Transcript Request</a></li>
  <li><a href="https://www.hancockcollege.edu/gratitude/index.php">Gratitude</a></li>
  <li><a href="https://www.hancockcollege.edu/health_services/index.php">Health Services</a></li>
  <li><a href="https://www.hancockcollege.edu/institutional_effectiveness/index.php">Institutional Effectiveness</a></li>
  <li><a href="https://www.hancockcollege.edu/institutional_grants/index.php">Institutional Grants</a></li>
  <li><a href="https://www.hancockcollege.edu/institutional_effectiveness/ilo.php">Institutional Learning Outcomes (ILOs)</a></li>
  <li><a href="https://www.hancockcollege.edu/planning/index.php">Institutional Planning</a></li>
  <li><a href="https://www.hancockcollege.edu/admissions_records/international.php">International Students</a></li>
  <li><a href="https://www.hancockcollege.edu/labs/index.php">Labs</a></li>
  <li><a href="https://www.hancockcollege.edu/languagelab/index.php">Language Lab</a></li>
  <li><a href="https://www.hancockcollege.edu/academic_departments/public_safety/law-enforcement/index.php">Law Enforcement&nbsp;Training</a></li>
  <li><a href="https://www.hancockcollege.edu/leap/index.php">LEAP</a></li>
  <li><a href="https://www.hancockcollege.edu/lap/index.php">Learning Assistance Program (LAP)</a></li>
  <li><a href="https://www.hancockcollege.edu/library/index.php">Library</a></li>
  <li><a href="http://www.hancockcollege.edu/public_affairs/logos.php">Logos</a></li>
  <li><a href="https://www.hancockcollege.edu/lompoc/index.php">Lompoc Valley Center</a></li>
  <li><a href="https://www.hancockcollege.edu/academic_departments/programs.php">Majors (Programs of Study)</a></li>
  <li><a href="https://www.hancockcollege.edu/public_affairs/locations.php">Maps</a></li>
  <li><a href="https://www.hancockcollege.edu/mathcenter/index.php">Math Center</a></li>
  <li><a href="https://www.hancockcollege.edu/mentorship/index.php">Mentorship</a></li>
  <li><a href="https://www.hancockcollege.edu/mesa/index.php">MESA Program</a></li>
  <li><a href="https://www.hancockcollege.edu/testing/multiplemeasures.php">Multiple Measures (English and Math Placement)</a></li>
  <li><a href="https://www.hancockcollege.edu/noncredit_counseling/index.php">Noncredit Counseling</a></li>
  <li><a href="https://www.hancockcollege.edu/counseling/workshops.php">Orientation/Advising</a></li>
  <li><a href="https://www.hancockcollege.edu/campus_police/parking.php">Parking</a></li>
  <li><a href="http://www.pcpa.org">PCPA - Pacific Conservatory Theatre</a></li>
  <li><a href="https://www.hancockcollege.edu/campus_police/index.php">Police</a></li>
  <li><a href="https://www.hancockcollege.edu/presidents_office/index.php">President's Office</a></li>
  <li><a href="https://www.hancockcollege.edu/pstc/index.php">Public Safety Training Complex (PSTC)</a></li>
  <li><a href="https://www.hancockcollege.edu/cashier_services/refunds.php">Refunds</a></li>
  <li><a href="https://www.hancockcollege.edu/admissions_records/index.php">Registration</a></li>
  <li><a href="https://www.hancockcollege.edu/roadmaps/index.php">Roadmaps to Success</a></li>
  <li><a href="https://www.hancockcollege.edu/syvc/index.php">Santa Ynez Valley Center</a></li>
  <li><a href="https://www.hancockcollege.edu/financial_aid/scholarships.php">Scholarships</a></li>
  <li><a href="https://www.hancockcollege.edu/community_education/index.php">Spectrum</a></li>
  <li><a href="https://www.hancockcollege.edu/mesa/STEMLL.php">STEM Center</a></li>
  <li><a href="https://www.hancockcollege.edu/ambassadors/index.php">Student Ambassadors</a></li>
  <li><a href="https://www.hancockcollege.edu/admissions_records/student-helpdesk.php">Student Helpdesk</a></li>
  <li><a href="https://www.hancockcollege.edu/current_students/student-services.php">Student Services</a></li>
  <li><a href="https://www.hancockcollege.edu/sustainability/index.php">Sustainability on Campus</a></li>
  <li><a href="https://www.hancockcollege.edu/testing/index.php">Testing Center</a></li>
  <li><a href="https://www.hancockcollege.edu/titleix/index.php">Title IX: Sexual Discrimination and Gender Equity</a></li>
  <li><a href="https://www.hancockcollege.edu/titlev/index.php">Title V</a></li>
  <li><a href="https://www.hancockcollege.edu/admissions_records/transcripts.php">Transcripts</a></li>
  <li><a href="https://www.hancockcollege.edu/transferdegrees/index.php">Transfer Degree Programs</a></li>
  <li><a href="https://www.hancockcollege.edu/tutoring/index.php">Tutorial Services</a></li>
  <li><a href="https://www.hancockcollege.edu/utc/index.php">University Transfer Center</a></li>
  <li><a href="https://www.hancockcollege.edu/veterans/index.php">Veteran Success Center</a></li>
  <li><a href="https://www.hancockcollege.edu/agribusiness/index.php">Wine - Viticulture and Enology</a></li>
  <li><a href="https://www.hancockcollege.edu/writing/index.php">Writing Center</a></li>
 </ul>