<ul>
  <li><a href="/admissions_records/calendar.php">Academic Calendar</a></li>
  <li><a href="/academic_departments/index.php">Academic Departments</a></li>
  <li><a href="/academic_senate/index.php">Academic Senate</a></li>
  <li><a href="/app/index.php">Academic Policy &amp; Planning (AP&amp;P)</a></li>
  <li><a href="/accreditation/index.php">Accreditation</a></li>
  <li><a href="/admissions_records/index.php">Admissions and Records</a></li>
  <li><a href="/asbg/clubs.php">AHC Clubs</a></li>
  <li><a href="/veterans/index.php">AHC Veteran Success Center (VSC)</a></li>
  <li><a href="/aim/index.php">AIM Center</a></li>
  <li><a href="/gallery/index.php">Art Gallery (Ann Foxworthy Gallery)</a></li>
  <li><a href="/asbg/index.php">ASBG</a></li>
  <li><a href="/employees/aux-accounting.php">Auxiliary Accounting Services</a></li>
  <li><a href="/auxilliarycorp/index.php">Auxiliary Programs Corporation</a></li>
  <li><a href="/laverne/index.php">Bachelor Programs</a></li>
  <li><a href="/board/index.php">Board of Trustees</a></li>
  <li><a href="/board/BoardPolicies.php">Board Policies</a></li>
  <li><a href="http://www.HancockCollegeShop.com">Bookstore</a></li>
  <li><a href="/bridges/index.php">Bridges to the Baccalaureate&nbsp;</a></li>
  <li><a href="/public_affairs/public-transportation.php">Bus Service/Transportation</a></li>
  <li><a href="/minicorps/index.php">California Mini Corps</a></li>
  <li><a href="/cal-soap/index.php">Cal-SOAP</a></li>
  <li><a href="/calworks/index.php">CalWORKs</a></li>
  <li><a href="/campuscruise/index.php">Campus Cruise (Tours)</a></li>
  <li><a href="/campus_graphics/index.php">Campus Graphics</a></li>
  <li><a href="/can/index.php">CAN/TRIO</a></li>
  <li><a href="https://hancockcollege.instructure.com/login/saml">Canvas</a></li>
  <li><a href="/care/index.php">CARE</a></li>
  <li><a href="/cte/index.php">Career Technical Education (CTE)</a></li>
  <li><a href="/cjpc/index.php">Career/Job Placement Center (CJPC)</a></li>
  <li><a href="/public_affairs/Catalog.php">Catalog</a></li>
  <li><a href="http://dfl.hancockcollege.edu/Presidents_Office/docs/CCPD Councils and Committees Manual.pdf">CCPD Councils and Committees Manual (PDF)</a></li>
  <li><a href="/childrens_center/index.php">Children's Center</a></li>
  <li><a href="http://bannerweb.hancockcollege.edu/prod/pw_sigsched.p_search">Class Search</a></li>
  <li><a href="/admissions_records/college-now.php">College Now!</a></li>
  <li><a href="/community_education/index.php">Community Education</a></li>
  <li><a href="/complaints/index.php">Complaints</a></li>
  <li><a href="/labs/computer_resources_center/index.php">Computer Resources Center</a></li>
  <li><a href="/concurrentenrollment/index.php">Concurrent Enrollment</a></li>
  <li><a href="/contracteducation/index.php">Contract Education</a></li>
  <li><a href="/cwe/index.php">Cooperative Work Experience (CWE)</a></li>
  <li><a href="/counseling/index.php">Counseling</a></li>
  <li><a href="/courserepeatability/index.php">Course Repeatability</a></li>
  <li><a href="/campus_police/clery.php">Crime Statistics</a></li>
  <li><a href="/cast/index.php">Crisis Intervention (CAST)</a></li>
  <li><a href="/degreeworks/index.php">DegreeWorks</a></li>
  <li><a href="/lap/index.php">Disability Services</a></li>
  <li><a href="/distance_learning/">Distance Learning</a></li>
  <li><a href="/dreamact/index.php">Dream Act/AB 540</a></li>
  <li><a href="/counseling/eap.php">Early Alert</a></li>
  <li><a href="/ewd/index.php">Economic and Workforce Development</a></li>
  <li><a href="/campus_police/emergency-prep.php">Emergency Preparedness</a></li>
  <li><a href="/placement/index.php">English and Math Placement</a></li>
  <li><a href="/eops/index.php">EOPS</a></li>
  <li><a href="/academic_departments/languages/esl/index.php">ESL-Credit</a>/li>
  <li><a href="/community_education/noncredit-esl.php">ESL-Noncredit</a></li>
  <li><a href="https://outreach.hancockcollege.edu/Ellucian.ERecruiting.Web.External/Pages/events.aspx">Event Registration</a></li>
  <li><a href="/facilities/index.php">Facilities</a></li>
  <li><a href="/cashier_services/index.php">Fees</a></li>
  <li><a href="/admissions_records/calendar.php">Final Exams</a></li>
  <li><a href="/financial_aid/index.php">Financial Aid</a></li>
  <li><a href="/foodshare/index.php">Food Share Because We Care</a></li>
  <li><a href="/cafyes/index.php">Foster Youth Services</a></li>
  <li><a href="/testing/ged.php">GED Computer-based Test</a></li>
  <li><a href="/testing/ged-esp.php">GED: por la computadora</a></li>
  <li><a href="/testing/gedtranscript.php">GED Transcript Request</a></li>
  <li><a href="/gratitude/index.php">Gratitude</a></li>
  <li><a href="/health_services/index.php">Health Services</a></li>
  <li><a href="/institutional_effectiveness/index.php">Institutional Effectiveness</a></li>
  <li><a href="/institutional_grants/index.php">Institutional Grants</a></li>
  <li><a href="/institutional_effectiveness/ilo.php">Institutional Learning Outcomes (ILOs)</a></li>
  <li><a href="/planning/index.php">Institutional Planning</a></li>
  <li><a href="/admissions_records/international.php">International Students</a></li>
  <li><a href="/labs/index.php">Labs</a></li>
  <li><a href="/languagelab/index.php">Language Lab</a></li>
  <li><a href="/academic_departments/public_safety/law-enforcement/index.php">Law Enforcement&nbsp;Training</a></li>
  <li><a href="/leap/index.php">LEAP</a></li>
  <li><a href="/lap/index.php">Learning Assistance Program (LAP)</a></li>
  <li><a href="/library/index.php">Library</a></li>
  <li><a href="http://www.hancockcollege.edu/public_affairs/logos.php">Logos</a></li>
  <li><a href="/lompoc/index.php">Lompoc Valley Center</a></li>
  <li><a href="/academic_departments/programs.php">Majors (Programs of Study)</a></li>
  <li><a href="/public_affairs/locations.php">Maps</a></li>
  <li><a href="/mathcenter/index.php">Math Center</a></li>
  <li><a href="/mentorship/index.php">Mentorship</a></li>
  <li><a href="/mesa/index.php">MESA Program</a></li>
  <li><a href="/testing/multiplemeasures.php">Multiple Measures (English and Math Placement)</a></li>
  <li><a href="/noncredit_counseling/index.php">Noncredit Counseling</a></li>
  <li><a href="/counseling/workshops.php">Orientation/Advising</a></li>
  <li><a href="/campus_police/parking.php">Parking</a></li>
  <li><a href="http://www.pcpa.org">PCPA - Pacific Conservatory Theatre</a></li>
  <li><a href="/campus_police/index.php">Police</a></li>
  <li><a href="/presidents_office/index.php">President's Office</a></li>
  <li><a href="/pstc/index.php">Public Safety Training Complex (PSTC)</a></li>
  <li><a href="/cashier_services/refunds.php">Refunds</a></li>
  <li><a href="/admissions_records/index.php">Registration</a></li>
  <li><a href="/roadmaps/index.php">Roadmaps to Success</a></li>
  <li><a href="/syvc/index.php">Santa Ynez Valley Center</a></li>
  <li><a href="/financial_aid/scholarships.php">Scholarships</a></li>
  <li><a href="/community_education/index.php">Spectrum</a></li>
  <li><a href="/mesa/STEMLL.php">STEM Center</a></li>
  <li><a href="/ambassadors/index.php">Student Ambassadors</a></li>
  <li><a href="/admissions_records/student-helpdesk.php">Student Helpdesk</a></li>
  <li><a href="/current_students/student-services.php">Student Services</a></li>
  <li><a href="/sustainability/index.php">Sustainability on Campus</a></li>
  <li><a href="/testing/index.php">Testing Center</a></li>
  <li><a href="/titleix/index.php">Title IX: Sexual Discrimination and Gender Equity</a></li>
  <li><a href="/titlev/index.php">Title V</a></li>
  <li><a href="/admissions_records/transcripts.php">Transcripts</a></li>
  <li><a href="/transferdegrees/index.php">Transfer Degree Programs</a></li>
  <li><a href="/tutoring/index.php">Tutorial Services</a></li>
  <li><a href="/utc/index.php">University Transfer Center</a></li>
  <li><a href="/veterans/index.php">Veteran Success Center</a></li>
  <li><a href="/agribusiness/index.php">Wine - Viticulture and Enology</a></li>
  <li><a href="/writing/index.php">Writing Center</a></li>
 </ul>